//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class value {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal value() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.value", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        internal static string Aciklama {
            get {
                return ResourceManager.GetString("Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adet ürün bulundu.
        /// </summary>
        internal static string Adet_urun_bulundu {
            get {
                return ResourceManager.GetString("Adet_urun_bulundu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        internal static string Adiniz {
            get {
                return ResourceManager.GetString("Adiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız Soyadınız.
        /// </summary>
        internal static string Adiniz_Soyadiniz {
            get {
                return ResourceManager.GetString("Adiniz_Soyadiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        internal static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfaya Dön.
        /// </summary>
        internal static string Anasayfa_Don {
            get {
                return ResourceManager.GetString("Anasayfa_Don", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Mesaj Gönderin.
        /// </summary>
        internal static string Bize_Mesaj_Gonderin {
            get {
                return ResourceManager.GetString("Bize_Mesaj_Gonderin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bize Ulaşın.
        /// </summary>
        internal static string Bize_Ulasin {
            get {
                return ResourceManager.GetString("Bize_Ulasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimle İletişime Geçin.
        /// </summary>
        internal static string Bizimle_Iletisime_Gec {
            get {
                return ResourceManager.GetString("Bizimle_Iletisime_Gec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detayı Gör.
        /// </summary>
        internal static string Detayi_Gor {
            get {
                return ResourceManager.GetString("Detayi_Gor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        internal static string Detaylar {
            get {
                return ResourceManager.GetString("Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylı Bilgi İçin.
        /// </summary>
        internal static string Detayli_Bilgi_icin {
            get {
                return ResourceManager.GetString("Detayli_Bilgi_icin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamı.
        /// </summary>
        internal static string Devami {
            get {
                return ResourceManager.GetString("Devami", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklenme Tarihi.
        /// </summary>
        internal static string EklenmeTarihi {
            get {
                return ResourceManager.GetString("EklenmeTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-KATALOG.
        /// </summary>
        internal static string E_Katalog {
            get {
                return ResourceManager.GetString("E_Katalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        internal static string E_Posta {
            get {
                return ResourceManager.GetString("E_Posta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global İnşaat, inşaat sektöründe güçlü bir geçmişe sahip, yenilikçi ve müşteri odaklı bir firmadır. 1990&apos;lı yılların başından bu yana, kaliteli işçilik ve güvenilir projelerle sektördeki varlığını sürdüren Global İnşaat, hem yurtiçinde hem de yurtdışında birçok önemli projeye imza atmıştır..
        /// </summary>
        internal static string footer_Hakkimizda {
            get {
                return ResourceManager.GetString("footer_Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız başarılı şekilde tarafımıza ulaşmıştır. Tarafınıza en kısa sürede dönüş yapılacaktır..
        /// </summary>
        internal static string formBasariliMesaj {
            get {
                return ResourceManager.GetString("formBasariliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj gönderme sırasında hata meydana geldi. Lütfen daha sonra tekrar deneyiniz..
        /// </summary>
        internal static string formHataliMesaj {
            get {
                return ResourceManager.GetString("formHataliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeri.
        /// </summary>
        internal static string Galeri {
            get {
                return ResourceManager.GetString("Galeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        internal static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu.
        /// </summary>
        internal static string Guvenlik_Kodu {
            get {
                return ResourceManager.GetString("Guvenlik_Kodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güvenlik Kodu Hatalı.
        /// </summary>
        internal static string Guvenlik_Kodu_Hatali {
            get {
                return ResourceManager.GetString("Guvenlik_Kodu_Hatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı Erişim.
        /// </summary>
        internal static string Hizli_Erisim {
            get {
                return ResourceManager.GetString("Hizli_Erisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizmetlerimiz.
        /// </summary>
        internal static string Hizmetlerimiz {
            get {
                return ResourceManager.GetString("Hizmetlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to için.
        /// </summary>
        internal static string icin {
            get {
                return ResourceManager.GetString("icin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Formu.
        /// </summary>
        internal static string iletisimFormu {
            get {
                return ResourceManager.GetString("iletisimFormu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıdaki formu doldurarak bizimle iletişime geçebilirsiniz..
        /// </summary>
        internal static string iletisim_AltBaslik {
            get {
                return ResourceManager.GetString("iletisim_AltBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        internal static string Iletisim_Bilgileri {
            get {
                return ResourceManager.GetString("Iletisim_Bilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İncele.
        /// </summary>
        internal static string incele {
            get {
                return ResourceManager.GetString("incele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        internal static string Konu {
            get {
                return ResourceManager.GetString("Konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menüler.
        /// </summary>
        internal static string Menuler {
            get {
                return ResourceManager.GetString("Menuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız.
        /// </summary>
        internal static string Mesajiniz {
            get {
                return ResourceManager.GetString("Mesajiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Bilgilendirme.
        /// </summary>
        internal static string Mesaj_Bilgilendirme {
            get {
                return ResourceManager.GetString("Mesaj_Bilgilendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Yollayın.
        /// </summary>
        internal static string Mesaj_Yollayin {
            get {
                return ResourceManager.GetString("Mesaj_Yollayin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projelerimiz.
        /// </summary>
        internal static string Projelerimiz {
            get {
                return ResourceManager.GetString("Projelerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referanslar.
        /// </summary>
        internal static string Referanslar {
            get {
                return ResourceManager.GetString("Referanslar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üzgünüz, aradığınız sayfa mevcut değil, kaldırılmış veya geçici olarak kullanılmıyor olabilir..
        /// </summary>
        internal static string SayfaBulanamadi_Aciklama {
            get {
                return ResourceManager.GetString("SayfaBulanamadi_Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Bulunamadı.
        /// </summary>
        internal static string Sayfa_Bulunamadi {
            get {
                return ResourceManager.GetString("Sayfa_Bulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global İnşaat: Sektörde&lt;br&gt;Mükemmelliğin Adı.
        /// </summary>
        internal static string Sidebar_Aciklama {
            get {
                return ResourceManager.GetString("Sidebar_Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya.
        /// </summary>
        internal static string Sosyal_Medya {
            get {
                return ResourceManager.GetString("Sosyal_Medya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyadınız.
        /// </summary>
        internal static string Soyadiniz {
            get {
                return ResourceManager.GetString("Soyadiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teklif Al.
        /// </summary>
        internal static string Teklif_Al {
            get {
                return ResourceManager.GetString("Teklif_Al", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm hakları saklıdır..
        /// </summary>
        internal static string TumHaklariSaklidir {
            get {
                return ResourceManager.GetString("TumHaklariSaklidir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        internal static string Tumu {
            get {
                return ResourceManager.GetString("Tumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümünü Gör.
        /// </summary>
        internal static string TumunuGor {
            get {
                return ResourceManager.GetString("TumunuGor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /blog.
        /// </summary>
        internal static string url_Blog {
            get {
                return ResourceManager.GetString("url_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        internal static string url_Folder {
            get {
                return ResourceManager.GetString("url_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /form-basarili.
        /// </summary>
        internal static string url_FormBasarili {
            get {
                return ResourceManager.GetString("url_FormBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /galeri.
        /// </summary>
        internal static string url_Galeri {
            get {
                return ResourceManager.GetString("url_Galeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /iletisim.
        /// </summary>
        internal static string url_Iletisim {
            get {
                return ResourceManager.GetString("url_Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /kategori.
        /// </summary>
        internal static string url_Kategori {
            get {
                return ResourceManager.GetString("url_Kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /kategoriler.
        /// </summary>
        internal static string url_Kategoriler {
            get {
                return ResourceManager.GetString("url_Kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /menu.
        /// </summary>
        internal static string url_Menu {
            get {
                return ResourceManager.GetString("url_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sayfa.
        /// </summary>
        internal static string url_Sayfa {
            get {
                return ResourceManager.GetString("url_Sayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /proje.
        /// </summary>
        internal static string url_Urun {
            get {
                return ResourceManager.GetString("url_Urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        internal static string Urunlerimiz {
            get {
                return ResourceManager.GetString("Urunlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaliteli ve Dayanıklı Ürünlerimiz.
        /// </summary>
        internal static string Urunlerimiz_AltBaslik {
            get {
                return ResourceManager.GetString("Urunlerimiz_AltBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama Alanları.
        /// </summary>
        internal static string Uygulama_Alanlari {
            get {
                return ResourceManager.GetString("Uygulama_Alanlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidrolik Teknolojilerimizin Hayat Bulduğu Sektörler.
        /// </summary>
        internal static string Uygulama_Alanlari_AltBaslik {
            get {
                return ResourceManager.GetString("Uygulama_Alanlari_AltBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp.
        /// </summary>
        internal static string whatsapp {
            get {
                return ResourceManager.GetString("whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp&apos;dan Sor.
        /// </summary>
        internal static string Whatsapp_Sor {
            get {
                return ResourceManager.GetString("Whatsapp_Sor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan Projeler.
        /// </summary>
        internal static string Yapilan_Projeler {
            get {
                return ResourceManager.GetString("Yapilan_Projeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Haberler.
        /// </summary>
        internal static string Yeni_Haberler {
            get {
                return ResourceManager.GetString("Yeni_Haberler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        internal static string Yorumlar {
            get {
                return ResourceManager.GetString("Yorumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Memnuniyeti Yorumları.
        /// </summary>
        internal static string Yorumlar_Alt_Baslik {
            get {
                return ResourceManager.GetString("Yorumlar_Alt_Baslik", resourceCulture);
            }
        }
    }
}
